[build]
  command = "npm run build --prefix client"
  publish = "client/build"
  functions = "netlify/functions"


[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200

[[redirects]]
  from = "/api/user-books/:username"
  to = "/.netlify/functions/userBooks"
  status = 200

[[redirects]]
  from = "/api/book/:username/:id"
  to = "/.netlify/functions/bookActions"
  status = 200

[[redirects]]
  from = "/api/book/:username"
  to = "/.netlify/functions/bookActions"
  status = 200
